version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: shh
      POSTGRES_DB: myDb
    volumes:
      - db-data:/var/lib/postgresql/data



volumes:
  db-data:
